import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/code/components/Layout/Header/Header";
import Footer from "@/code/components/Layout/Footer";
import { ContextProvider } from "@/code/typescript/context/Provider";
import Marquee, { MarqueeReverse } from "@/code/components/Home/Marquee";
import { AOSInit } from "@/code/typescript/context/AOSInit";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nona's",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AOSInit />
        <ContextProvider>
        <Header/>
        {children}
        <Footer/>
        <Marquee/>
      </ContextProvider>
      </body>
    </html>
  );
}
